// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package model

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type resource_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var ResourceBinding = resource_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 3979277378798837263,
}

// Resource_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Resource_ = struct {
	ID           *objectbox.PropertyUint64
	Title        *objectbox.PropertyString
	ResourceType *objectbox.PropertyInt64
	Description  *objectbox.PropertyString
	Regions      *objectbox.PropertyStringVector
	Comment      *objectbox.PropertyString
	URL          *objectbox.PropertyString
	Tags         *objectbox.PropertyStringVector
	License      *objectbox.PropertyStringVector
	Browser      *objectbox.PropertyStringVector
}{
	ID: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &ResourceBinding.Entity,
		},
	},
	Title: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &ResourceBinding.Entity,
		},
	},
	ResourceType: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &ResourceBinding.Entity,
		},
	},
	Description: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &ResourceBinding.Entity,
		},
	},
	Regions: &objectbox.PropertyStringVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &ResourceBinding.Entity,
		},
	},
	Comment: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &ResourceBinding.Entity,
		},
	},
	URL: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &ResourceBinding.Entity,
		},
	},
	Tags: &objectbox.PropertyStringVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &ResourceBinding.Entity,
		},
	},
	License: &objectbox.PropertyStringVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &ResourceBinding.Entity,
		},
	},
	Browser: &objectbox.PropertyStringVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &ResourceBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (resource_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (resource_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Resource", 1, 3979277378798837263)
	model.Property("ID", 6, 1, 310324367271568826)
	model.PropertyFlags(1)
	model.Property("Title", 9, 2, 8746423320512736329)
	model.Property("ResourceType", 6, 3, 7535355438529720560)
	model.Property("Description", 9, 4, 3072999814435305093)
	model.Property("Regions", 30, 5, 4022568439416524261)
	model.Property("Comment", 9, 6, 5767748824699061826)
	model.Property("URL", 9, 7, 9212575716174209430)
	model.Property("Tags", 30, 8, 2140856262330507356)
	model.Property("License", 30, 9, 6438982053546495694)
	model.Property("Browser", 30, 10, 5050549190669747951)
	model.EntityLastPropertyId(10, 5050549190669747951)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (resource_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Resource).ID, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (resource_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Resource).ID = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (resource_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (resource_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Resource)
	var propResourceType int64
	{
		var err error
		propResourceType, err = resourceTypeInt64ToDatabaseValue(obj.ResourceType)
		if err != nil {
			return errors.New("converter resourceTypeInt64ToDatabaseValue() failed on Resource.ResourceType: " + err.Error())
		}
	}

	var offsetTitle = fbutils.CreateStringOffset(fbb, obj.Title)
	var offsetDescription = fbutils.CreateStringOffset(fbb, obj.Description)
	var offsetRegions = fbutils.CreateStringVectorOffset(fbb, obj.Regions)
	var offsetComment = fbutils.CreateStringOffset(fbb, obj.Comment)
	var offsetURL = fbutils.CreateStringOffset(fbb, obj.URL)
	var offsetTags = fbutils.CreateStringVectorOffset(fbb, obj.Tags)
	var offsetLicense = fbutils.CreateStringVectorOffset(fbb, obj.License)
	var offsetBrowser = fbutils.CreateStringVectorOffset(fbb, obj.Browser)

	// build the FlatBuffers object
	fbb.StartObject(10)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetTitle)
	fbutils.SetInt64Slot(fbb, 2, propResourceType)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetRegions)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetComment)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetURL)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetDescription)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetTags)
	fbutils.SetUOffsetTSlot(fbb, 8, offsetLicense)
	fbutils.SetUOffsetTSlot(fbb, 9, offsetBrowser)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (resource_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Resource' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propID = table.GetUint64Slot(4, 0)

	propResourceType, err := resourceTypeInt64ToEntityProperty(fbutils.GetInt64Slot(table, 8))
	if err != nil {
		return nil, errors.New("converter resourceTypeInt64ToEntityProperty() failed on Resource.ResourceType: " + err.Error())
	}

	return &Resource{
		ID:           propID,
		Title:        fbutils.GetStringSlot(table, 6),
		ResourceType: propResourceType,
		Regions:      fbutils.GetStringVectorSlot(table, 12),
		Comment:      fbutils.GetStringSlot(table, 14),
		URL:          fbutils.GetStringSlot(table, 16),
		Description:  fbutils.GetStringSlot(table, 10),
		Tags:         fbutils.GetStringVectorSlot(table, 18),
		License:      fbutils.GetStringVectorSlot(table, 20),
		Browser:      fbutils.GetStringVectorSlot(table, 22),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (resource_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Resource, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (resource_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Resource), nil)
	}
	return append(slice.([]*Resource), object.(*Resource))
}

// Box provides CRUD access to Resource objects
type ResourceBox struct {
	*objectbox.Box
}

// BoxForResource opens a box of Resource objects
func BoxForResource(ob *objectbox.ObjectBox) *ResourceBox {
	return &ResourceBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Resource.ID property on the passed object will be assigned the new ID as well.
func (box *ResourceBox) Put(object *Resource) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Resource.ID property on the passed object will be assigned the new ID as well.
func (box *ResourceBox) Insert(object *Resource) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *ResourceBox) Update(object *Resource) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *ResourceBox) PutAsync(object *Resource) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case IDs are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Resource.ID property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Resource.ID assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *ResourceBox) PutMany(objects []*Resource) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *ResourceBox) Get(id uint64) (*Resource, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Resource), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *ResourceBox) GetMany(ids ...uint64) ([]*Resource, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Resource), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *ResourceBox) GetManyExisting(ids ...uint64) ([]*Resource, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Resource), nil
}

// GetAll reads all stored objects
func (box *ResourceBox) GetAll() ([]*Resource, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Resource), nil
}

// Remove deletes a single object
func (box *ResourceBox) Remove(object *Resource) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *ResourceBox) RemoveMany(objects ...*Resource) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.ID
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Resource_ struct to create conditions.
// Keep the *ResourceQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *ResourceBox) Query(conditions ...objectbox.Condition) *ResourceQuery {
	return &ResourceQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Resource_ struct to create conditions.
// Keep the *ResourceQuery if you intend to execute the query multiple times.
func (box *ResourceBox) QueryOrError(conditions ...objectbox.Condition) (*ResourceQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &ResourceQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See ResourceAsyncBox for more information.
func (box *ResourceBox) Async() *ResourceAsyncBox {
	return &ResourceAsyncBox{AsyncBox: box.Box.Async()}
}

// ResourceAsyncBox provides asynchronous operations on Resource objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type ResourceAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForResource creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use ResourceBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForResource(ob *objectbox.ObjectBox, timeoutMs uint64) *ResourceAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &ResourceAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the ID property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *ResourceAsyncBox) Put(object *Resource) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The ID property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *ResourceAsyncBox) Insert(object *Resource) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *ResourceAsyncBox) Update(object *Resource) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *ResourceAsyncBox) Remove(object *Resource) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Resource which ID is either 42 or 47:
// 		box.Query(Resource_.ID.In(42, 47)).Find()
type ResourceQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *ResourceQuery) Find() ([]*Resource, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Resource), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *ResourceQuery) Offset(offset uint64) *ResourceQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *ResourceQuery) Limit(limit uint64) *ResourceQuery {
	query.Query.Limit(limit)
	return query
}
